In [39]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [18]:
type(list_)

list

In [27]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [57]:
for i in list_:
    print("Element",i,"data type is",type(i))

Element 1 data type is <class 'str'>
Element 2 data type is <class 'str'>
Element 3 data type is <class 'str'>
Element 4 data type is <class 'str'>
Element 5 data type is <class 'str'>


In [55]:
for i in array_list:
    print("Element",i ,"data type is" ,  type(i))

Element 1 data type is <class 'numpy.str_'>
Element 2 data type is <class 'numpy.str_'>
Element 3 data type is <class 'numpy.str_'>
Element 4 data type is <class 'numpy.str_'>
Element 5 data type is <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [28]:
array_list = np.array(object = list_, dtype = int)

In [29]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [30]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [31]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [32]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [33]:
num_array.shape

(2, 3)

In [34]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [36]:
import numpy as np
np.zeros((3 , 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [38]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])